#  Indicadores  {#intro}



Los indicadores, es el plural del término “indicador” y precisamente, como dice su nombre lo dice, es un elemento que se utiliza para indicar o señalar algo. En el sentido más formal, un indicador es una herramienta cuantitativa o cualitativa que brinda una señal con una interpretación única y lógica. En efecto, debe comprenderse que los indicadores tienen un objetivo en concreto con la intención de poder monitorear, adaptar y controlar distintos procedimientos a seguir. De ahí, resulta necesario decir que un indicador debe representar la relación entre dos o más variables a fin de que sea más simple el análisis y la toma de decisiones respecto a la gestión de los resultados.

Existen diferentes maneras de clasificar los indicadores, dependiendo de su función y contexto en donde este actúa. A continuación describiremos sólo tres tipos de indicadores con el fin de que el lector  pueda identificar su alcance frente a cualquier campo. Para empezar, mencionamos en qué consisten los *indicadores de eficacia*. Estos tienen como propósito medir el grado de cumplimiento de una meta o un resultado propuesto. Asimismo, le sigue los *indicadores de eficiencia* que  miden el nivel de ejecución del proceso teniendo en cuenta la relación entre el logro del programa y los recursos utilizados para su cumplimiento mediante el tiempo, el esfuerzo o el costo. Por último, están los *indicadores de calidad*, como su nombre lo dice, consiste en medir el nivel de calidad de un proceso o servicio mediante diferentes perspectivas como el nivel de satisfacción o la precisión en la ejecución del proceso.

Para poder entender mejor lo anterior, daremos algunos ejemplos a grandes rasgos desde la perspectiva de la universidad y cómo actúan los indicadores a partir de un objetivo establecido.


```{r, echo=FALSE}
library(tidyr)
intro <- tibble(`Dependencia` = c("Bienestar universitario","Dirección académica","Investigación","Planeación institucional"), `Objetivo` = c("Mantener la acreditación institucional y de alta calidad de sus programas académicos.","Contribuir a la internacionalización y bilingüismo como necesidad de la interacción con comunidades extranjeras. ","Fomentar el desarrollo de investigación formativa e investigación científica en cada programa académico.","Contribuir al desarrollo de políticas institucionales de buen gobierno que garanticen la estabilidad de cada programa académico."), `Indicadores` = c("* Determinar el nivel de satisfacción en los usuarios de los servicios ofrecidos por Bienestar. <br> * El porcentaje  de estudiantes que califica con satisfacción alta o muy alta los servicios ofrecidos por bienestar académico.","* Medir el crecimiento de estudiantes extranjeros activos en la universidad.<br> * Costo que vale para la universidad dar un acompañamiento y seguimiento a un estudiante extranjero.<br> * Número de cursos de diferentes  idiomas no remotos ofertados por la universidad.","* Porcentaje de grupos de investigación activos en la universidad. <br> * Número de eventos, seminarios o espacios de difusión para compartir resultados y experiencias de un tema en común. <br> * Número de horas semanales dedicadas por cada estudiante al grupo de investigación.","* Determinar el nivel de participación entre cada ente que conforma la comunidad universitaria. <br> * Número de espacios asamblearios en cada programa académico de la universidad."))
knitr::kable(intro, caption = 'Ejemplos de indicadores')

```

Como bien  fue dicho, un indicador debe presentar la relación entre dos variables para ello es necesario definir un método de cálculo para el indicador. Por consiguiente, es preciso comprender la proporción, el porcentaje, la razón, la tasa de variación y el índice como métodos de cálculo más utilizados.  Para ello, haremos un estudio detallado desde la estructura y el comportamiento matemático de cada uno de estos métodos. 















