# Tasas {#tasas}
Una tasa es una razón entre dos cantidades con unidades distintas y expresan la dinámica de un suceso en una población a lo largo del tiempo. Si la tasa o la cantidad frente a la cual algo está cambiando no está especificada, usualmente la tasa es por unidad de tiempo.  Sin embargo, una tasa  puede ser especificada por unidad de tiempo, por unidad de medida o masa o cualquier otra cantidad. Naturalmente para describir las unidades de una tasa, la palabra "por" se utiliza para poder separar las unidades de dos medidas utilizadas para calcular la tasa como, por ejemplo, pesos por libra, metros por segundo, millas por hora, y días enfermo por año. De aquí es conveniente clasificar algunas tasas cuando *el denominador es una variable temporal, un “stock” poblacional* ó *una variable monetaria*.

***1. Cuando el denominador es un “stock” poblacional***. Haciendo referencia a un “stock” poblacional como las poblaciones en un punto exacto de tiempo y tienen como fuentes los censos, padrones, estimaciones de población o encuestas. Para el cálculo, el numerador expresa el número de eventos ocurridos en una población durante un período. Como afirma @moreno2000principales, a diferencia de las [proporciones](#proporcion), el denominador  no expresa el número de sujetos en observación sino el tiempo durante el cual tales sujetos estuvieron en riesgo de sufrir el evento. Así que, la tasa se calcula mediante la siguiente fórmula<br>

$\frac{\text{Número de eventos ocurridos en un población en el periodo t}}{\text{Sumatoria de los periodos donde los individuos de la población libres del evento estuvieron expuestos al riesgo en el periodo t}}\times 10^n$


La unidad de medida empleada se conoce como *tiempo-persona* de seguimiento. Por ejemplo, la observación de 100 individuos libres del evento durante un año corresponde a 100 años-persona de seguimiento; de manera similar, 10 sujetos observados durante diez años corresponden a 100 años-persona. Entonces, la población $n$ en observación durante un año corresponde a $n$ año-persona. Así que, esto explica por qué en los ejemplos clásicos sobre tasas en epidemiología (algunos se presentarán a continuación) que corresponden a estudios hechos durante un período de un año, la sumatoria de los períodos donde los individuos de la población libres del evento estuvieron expuestos al "riesgo" en el periodo de un año (el denominador de la tasa) coindice con la población en observación.


* *Tasa de natalidad:* Es el número de nacimientos de una población por cada $10^n$ habitantes en un año. <br>
$$\frac{\text{Número de nacimientos en un periodo de tiempo}}{\text{Población media en ese periodo}}\times 10^n$$


El uso de la constante $10^n$, responde a la necesidad de comunicar el indicador de una manera comprensible y de fácil uso o recordación con el fin de permitir rápidamente su comparación con otros hechos. 

|Ejemplo. *Tasa de natalidad de una población* |
|--------------------------------------------------------------------|
|En una población nacieron $73.010$ niños a la fecha frente a una población de $5'000.000$ habitantes. La tasa de natalidad a la fecha es $\frac{73.010}{5'000.000}\times 1.000=14,6$.|

La tasa de natalidad será de $0,0146$. No obstante, al usar el factor de $1.000$ la cifra se presenta como "$14,6$ nacimientos por cada $1.000$ habitantes" lo cual es evidentemente más claro.

* *Tasa de mortalidad:* Es el número de fallecimientos con respecto a la población total por cada $10^n$ habitantes en un año. <br>
$$\frac{\text{Número de defunciones en un periodo de tiempo}}{\text{Población media en ese período}}\times 10^n$$

No siempre el “stock” poblacional representa la población media de una región. También puede ser una población con alguna característica en cuestión, como lo veremos a continuación: 

* *Tasa de prevalencia:* Es una medida que dice cuántas personas sufren una enfermedad en un momento específico.

$$\begin{equation}
\frac{\text{Número de personas con la enfermedad en un periodo de tiempo}}{\text{Número de personas en la población expuesta al riesgo
en el momento}}\times 10^{n}
\end{equation}$$

* *Tasa de letalidad:* Indica qué proporción de los diagnosticados con una enfermedad mueren por esa causa y su fórmula de cálculo es la siguiente:

$$\begin{equation}
\frac{\text{Número de muertes por una enfermedad en un período de tiempo}}{\text{Población diagnosticada de la enfermedad en ese periodo}}\times 10^n
\end{equation}$$

|Ejemplo. *Letalidad del cáncer de páncreas*|
|--------------------------------------------------------------------|
|En una población murieron $266$ personas por cáncer de páncreas en el 2016 frente a un total de $278$ personas diagnosticadas con cáncer de páncreas en ese mismo año. Se calcula que la tasa de letalidad sería  $\frac{266}{278}\times 100=95,7\%$.|

***2. Cuando el denominador es una variable temporal***. Mide la frecuencia con la que, en un período de tiempo, aparece un suceso en una población. El cálculo de tasas se realiza dividiendo el total de eventos ocurridos en un periodo dado en una población entre el tiempo de observación en el que ocurrieron dichos eventos. Las tasas se expresan multiplicando el resultado obtenido por una potencia de $10$, que puede variar entre $10$ y $100.000$.

$$\begin{equation}
\frac{\text{Número de eventos sucedidos}}{\text{Período en que fueron observados}}\times 10^{n}
\end{equation}$$

En efecto, magnitudes vectoriales como la velocidad que describe el cambio de posición con respecto al tiempo y la aceleración, el cambio de velocidad por unidad de tiempo son  ejemplos de tasas muy comunes según esta clasificación. En otras áreas, también encontramos la tasa de flujo volumétrico, el cual relaciona el volumen de un líquido que pasa a través de un superficie dado por unidad temporal o la tasa de bits, en computación, que relaciona el número de bits enviados o procesados por un computador por unidad temporal.

***3. Cuando el denominador es una variable monetaria.*** 

* *Tasa de cambio:* La tasa de cambio muestra la relación que existe entre dos monedas. Dicha tasa es un indicador que expresa cuántas unidades de una divisa se necesitan para obtener una unidad de la otra. En el caso de Colombia, tenemos la siguiente relación o también véase @BibEntry2019Jun.

$$\begin{equation}
\frac{\text{Cantidad o peso de la moneda local}}{\text{Una unidad de la moneda extrajera}}\times 10^{n}
\end{equation}$$

|Ejemplo. *Tasa de cambio entre el euro y el dólar*|
|--------------------------------------------------------------------|
|Si la tasa de cambio entre el euro y el dólar estadounidense fuera de 2,54. Esto implica a que el euro equivale a $2,54$ dólares, es decir, $\frac{2,54 \hspace{2mm} \text{dólares}}{1 \hspace{2mm}\text{euro}}= 2,54$.  |

* *Tasa Impositiva:* Se aplica para el pago de impuestos de una empresa. 

$$\begin{equation}
\frac{\text{Impuestos pagados por la empresa en un periodo }}{\text{Ingresos obtenidos en el mismo periodo }}\times 10^{n}
\end{equation}$$

## Tasas en el mercado laboral
 
Las tasas en el mercado laboral proporciona información sobre el estado de la fuerza de trabajo (empleo, desempleo o inactividad) de la población del país.
 
 En Colombia, según @DeCastroRamos2021Sep se tiene en cuenta las siguientes razones y se consideran que son válidas de desempleo.
 
a. No hay trabajo disponible en la ciudad.
b. Está esperando que lo llamen.
c. No sabe cómo buscar trabajo.
d. Está cansado de buscar trabajo.
e. No encuentra trabajo apropiado en su oficio o profesión.
f. Está esperando la temporada alta.
g. Carece de la experiencia necesaria.
h. No tiene recursos para instalar un negocio.
i. Los empleadores lo consideran muy joven o muy viejo

Caso contrario, las que no se consideran válidas son:

a. Se considera muy joven o muy viejo.
b. Actualmente no desea conseguir trabajo.
c. Responsabilidades familiares.
d. Problemas de salud.
e. Está estudiando.
f. Otra razón


### Tasa de desempleados (TD):

Es la relación porcentual entre el número de personas que están
buscando trabajo (DS), y el número de personas que integran la fuerza laboral (PEA) <br>

$$\frac{\text{DS}}{\text{PEA}}\times 100$$

donde el PEA está constituida por las personas de 12 y más años en la parte urbana, y de 10 años y más en la parte rural.

### Tasa de ocupación (TO)

Es la relación porcentual entre la población ocupada (OC) y el
número de personas que integran la población en edad de trabajar (PET).

$$\frac{\text{OC}}{\text{PET}}\times 100$$

donde PET también se llama fuerza laboral y son las personas en edad de trabajar, que trabajan o están buscando empleo.

## Tasa de Variación {#tasavariación}

Representa la razón de dos observaciones de una misma variable pero en dos diferentes puntos del tiempo (pasado y presente), por lo que expresa un cambio porcentual en el tiempo. La observación más reciente se coloca en el numerador mientras que la menos reciente se coloca en el denominador. Es decir para $t,k$ números enteros, la tasa de variación se expresa como,

$$\begin{equation}
\frac{\text{(Variable en el periodo}\hspace{2mm} t)-(\text{Variable en el periodo} \hspace{2mm} t-k)}{\text{Variable en el periodo} \hspace{2mm} t-k} \hspace{8mm} \text{(1)}
\end{equation}$$

donde el numerador indica el cambio de la variable en relación a dichos periodos. En otras palabras, al ser una razón, se está comparando el cambio de la variable en dos períodos con la variable en el período menos reciente.  Es equivalente de $(1)$ expresarlo

$$\begin{equation}
\frac{\text{Variable en el periodo}\hspace{2mm} t}{\text{Variable en el periodo} \hspace{2mm} t-k}-1
\end{equation}$$

finalmente se multiplica por $10^{n}$ para expresar la tasa como una potencia de $10$.

$$\begin{equation}
\left[\frac{\text{Variable en el periodo}\hspace{2mm} t}{\text{Variable en el periodo} \hspace{2mm} t-k}-1 \right] \times 10^{n}.
\end{equation}$$

Ahora es conveniente mencionar algunos ejemplos en donde se calcula la tasa de variación dado un indicador.

```{r, echo=FALSE}
library(tidyr)
ind5 <- tibble(`Nombre del indicador` = c("Tasa de variación del total de libros publicados en la Universidad con o sin sello editorial entre los años $2019-2020$.","Tasa de variación del total de docentes en la Universidad entre los semestres $2008-II$ y $2020-I$.","Tasa de variación del total de estudiantes matriculados en la Universidad entre los semestres $2009-II$ y $2020-I$."), `Método de cálculo` = c("[(Total del libros publicados en el año $2020 /$ Total de libros publicados en el año $2019$)$-1$]$×100$ ", "[(Total de docentes  en el semestre $2020-I /$ Total de docentes en el semestre $2008-II$)$-1$]$×100$", "[(Total de estudiantes matriculados en el semestre $2020-I /$ Total de estudiantes matriculados en el semestre $2009-II$)$-1$]$×100$"), `Procedimiento` = c("[${410}/{400}-1$]$×100=2,5$%", "[${3.113}/{2.940}-1$]$×100=5,8$%","[${54.284}/{45.200}-1$]$×100=20$%"))
knitr::kable(ind5, caption = 'Tasas de variaciones de la Universidad Nacional' )
```

En la economía, encontramos otros ejemplos de tasa de variación.

* ***Tasa de inflación:*** Muestra la variación porcentual de los precios de un determinado territorio, durante un periodo determinado y con esto, podemos saber cómo se han comportado los precios en un lugar determinado. El cálculo de esta tasa se determina en términos del [Índice de Precios al Consumidor (IPC)](#ipc).

$$\begin{equation}
\left[\frac{\text{IPC actual}}{\text{IPC anterior}}-1\right]\times 10^{n}
\end{equation}$$

* ***Tasa de crecimiento económico:*** Es la variación porcentual del PIB (Producto Interno Bruto) en un periodo de tiempo determinado en el que pemite calcular cual ha sido el aumento de la cantidad de bienes y servicios que produce una economía [@de2009producto].

$$\begin{equation}
\left[\frac{\text{PIB actual}}{\text{PIB anterior}}-1\right]\times 10^{n}
\end{equation}$$